### ISSUE TITLE
Missing list index number in the path

### ISSUE THREAD

**Issue by MurzNN** [sm-moore/yaml-path#4]
The path generates well with dict items, but with lists items it misses the numeric index of it.
For example:
```yaml
ingress:
  main:
    hosts:
      -  host: host1
      -  host: host2
      -  host: host3
```
And the last key should generate the path `ingress.main.hosts.2.host` (or `ingress.main.hosts[2].host`?) but the extension generates just `ingress.main.hosts.host`.
Could you please fix this? Thanx!
