### ISSUE TITLE
Comments on keys should be ignored

### ISSUE THREAD

**Issue by boekhold** [sm-moore/yaml-path#7]
Take this YAML example:
```yaml
key1:
  key2: # This is key 2
    param: value
```
The YAML Path is rendered as `key1.key2: # This is key 2.param`. Expected path is `key1.key2.param`.
